---
name: CI

on: [push, pull_request]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3.8 -m pip install setuptools wheel twine
      - name: Build packages
        run: |
          python3.8 utils/build-dists.py
      - name: Check packages
        run: |
          set -exo pipefail;
          if [ $(python3.8 -m twine check dist/* | grep -c 'warning') != 0 ]; then exit 1; fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3.8 -m pip install nox
      - name: Lint the code
        run: nox --no-error-on-missing-interpreter -s lint

  test-build-distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install build tools
        run: |
          python3.7 -m pip install --upgrade build
      - name: Build project for distribution
        run: |
          python3.7 -m build

  test-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python 3.8 for Nox
        if: matrix.python-version != '3.8'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install nox
        run: |
          python3.8 -m pip install nox
      - name: Run Tests
        run: |
          nox --no-error-on-missing-interpreter -rs lint test
