name: Integration with Unreleased OpenSearch

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { opensearch_ref: '1.x' }
          - { opensearch_ref: '2.x' }
          - { opensearch_ref: '2.0' }
          - { opensearch_ref: 'main' }
    steps:
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/opensearch
          ref: ${{ matrix.entry.opensearch_ref }}
          path: opensearch

      - name: Assemble OpenSearch
        run: |
          cd opensearch
          ./gradlew assemble

        # This step runs the docker image generated during gradle assemble in OpenSearch. It is tagged as opensearch:test.
        # Reference: https://github.com/opensearch-project/OpenSearch/blob/2.0/distribution/docker/build.gradle#L190
      - name: Run Docker Image
        run: |
          docker run -p 9200:9200 -p 9600:9600 -d -e "discovery.type=single-node" -e "bootstrap.memory_lock=true" opensearch:test
          sleep 90

      - name: Checkout High Level Python Client
        uses: actions/checkout@v2

      - name: Install Nox
        run: pip install nox

      - name: Run integration tests
        run: |
          nox -rs lint test